/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package my.desktop;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author inf.desderil1609
 */
public class FrontEnd extends javax.swing.JFrame {

    /**
     * Creates new form FrontEnd
     */
    public FrontEnd() {
        initComponents();
        //listener del bottone btnPacchi per l'apertura del db dei Pacchi
        btnPacchi.addActionListener(new ActionListener(){      
                private String url = null;
                String query = null;
                
            public void actionPerformed(ActionEvent e){
                
                tblDatabase.clearSelection();
                //il resultSet è set di dati che rapresenta un insieme di risultati del db, lo si ottiene interrogando un db
                ResultSet rs;
                url = ("url");
                query = "SELECT * FROM Pacchi";
                
                try{
                    //Stà ad identificare una connessione con un database specifico
                    Connection conn = DriverManager.getConnection(url);
                    
                    PreparedStatement stm = conn.prepareStatement(query);
                    rs = stm.executeQuery();
                    //rs.next restituisce un booleano, sposta il cursore sulla riga successiva del set dei rusultati del db e restituisce true se è presente una riga piena
                    if(rs.next()){
                        dispose();
                        tblDatabase.setVisible(true);
                        
                    }
                    
                    
                }catch (SQLException ex){
                
                    JOptionPane.showMessageDialog(null, ex);
                }
            }
        
        });
        //listener del bottone btnFattorini per l'apertura del db dei fattorini
        btnFattorini.addActionListener(new ActionListener(){
        
            public void actionPerformed(ActionEvent e){
                            
            }
        
        });
        //listener del bottone btnAggPacco dove si da la possibilità di inserire una nuova righa nel db Pacchi
        btnAggPacco.addActionListener(new ActionListener(){
        
            public void actionPerformed(ActionEvent e){
                            
            }
        
        });
        //listener del bottone btnAggFatt dove si da la possibilità di inserire una nuova righa nel db Fattorini   
        btnAggFatt.addActionListener(new ActionListener(){
        
            public void actionPerformed(ActionEvent e){
                            
            }
        
        });
        //listener del bottone btnRimPacco dove si da la possibilità di eliminare una determinata riga all'interno del db Pacchi
        btnRimPacco.addActionListener(new ActionListener(){
        
            public void actionPerformed(ActionEvent e){
                            
            }
        
        });
        //listener del bottone btnRimFatt dove si da la possibilità di eliminare una determinata riga all'interno del db Fattorini
        btnRimFatt.addActionListener(new ActionListener(){
        
            public void actionPerformed(ActionEvent e){
                            
            }
        
        });
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        btnPacchi = new javax.swing.JButton();
        btnFattorini = new javax.swing.JButton();
        lblCerca = new javax.swing.JLabel();
        btnCerca = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCerca = new javax.swing.JTextPane();
        btnAggPacco = new javax.swing.JButton();
        btnAggFatt = new javax.swing.JButton();
        btnRimPacco = new javax.swing.JButton();
        btnRimFatt = new javax.swing.JButton();
        jspTable = new javax.swing.JScrollPane();
        tblDatabase = new javax.swing.JTable();
        btnModPacco = new javax.swing.JButton();
        btnModFatt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ApplicazioneDesktop");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnPacchi.setText("Visualizza Tabella Pacchi");
        btnPacchi.setName(""); // NOI18N

        btnFattorini.setText("Visualizza Tabella Fattorini");

        lblCerca.setText("Cerca...");

        btnCerca.setText("Cerca");

        jScrollPane1.setViewportView(txtCerca);
        txtCerca.getAccessibleContext().setAccessibleName("txtRicerca");

        btnAggPacco.setText("Aggiungi Pacco");
        btnAggPacco.setMaximumSize(new java.awt.Dimension(123, 23));
        btnAggPacco.setMinimumSize(new java.awt.Dimension(123, 23));

        btnAggFatt.setText("Aggiungi Fattorini");

        btnRimPacco.setText("Rimuovi Pacco");
        btnRimPacco.setMaximumSize(new java.awt.Dimension(123, 23));
        btnRimPacco.setMinimumSize(new java.awt.Dimension(123, 23));

        btnRimFatt.setText("Riumuovi Fattorino");

        tblDatabase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jspTable.setViewportView(tblDatabase);

        btnModPacco.setText("Modifica Pacco");
        btnModPacco.setMaximumSize(new java.awt.Dimension(123, 23));
        btnModPacco.setMinimumSize(new java.awt.Dimension(123, 23));

        btnModFatt.setText("Modifica Fattorini");
        btnModFatt.setMaximumSize(new java.awt.Dimension(123, 23));
        btnModFatt.setMinimumSize(new java.awt.Dimension(123, 23));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jspTable)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPacchi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAggPacco, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40))
                            .addComponent(btnAggFatt)
                            .addComponent(btnModPacco, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnModFatt, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRimFatt)
                            .addComponent(btnRimPacco, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnFattorini)
                                .addGap(74, 74, 74)
                                .addComponent(lblCerca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCerca)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jspTable, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPacchi)
                        .addComponent(btnFattorini)
                        .addComponent(lblCerca))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnCerca)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAggPacco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRimPacco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAggFatt)
                    .addComponent(btnRimFatt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModPacco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModFatt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        btnPacchi.getAccessibleContext().setAccessibleName("btnPacchi");
        btnFattorini.getAccessibleContext().setAccessibleName("btnFattorini");
        lblCerca.getAccessibleContext().setAccessibleName("lblRicerca");
        btnCerca.getAccessibleContext().setAccessibleName("BtnCerca");
        btnAggPacco.getAccessibleContext().setAccessibleName("btnAggiuntaPacchi");
        btnAggFatt.getAccessibleContext().setAccessibleName("btnAggiuntaFattorini");
        btnRimPacco.getAccessibleContext().setAccessibleName("btnRimozionePacco");
        btnRimFatt.getAccessibleContext().setAccessibleName("btnRimozioneFattorini");
        btnModPacco.getAccessibleContext().setAccessibleName("btnModPacco");
        btnModFatt.getAccessibleContext().setAccessibleName("btnModFatt");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrontEnd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrontEnd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrontEnd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrontEnd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrontEnd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAggFatt;
    private javax.swing.JButton btnAggPacco;
    private javax.swing.JButton btnCerca;
    private javax.swing.JButton btnFattorini;
    private javax.swing.JButton btnModFatt;
    private javax.swing.JButton btnModPacco;
    private javax.swing.JButton btnPacchi;
    private javax.swing.JButton btnRimFatt;
    private javax.swing.JButton btnRimPacco;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JScrollPane jspTable;
    private javax.swing.JLabel lblCerca;
    private javax.swing.JTable tblDatabase;
    private javax.swing.JTextPane txtCerca;
    // End of variables declaration//GEN-END:variables
}
